### PR TITLE
deploy snapshot as build artifact

### PR DESCRIPTION
**Pull request by rkaminsk**
@kherud, I found some time to automate the build process of the jar. It includes libraries for linux, macos, and windows. A snapshot is build whenever something is committed to the master.

From here it would also be easy to deploy the jar somewhere. I have no experience with this however. Maybe one could bundle all dependencies in the jar or upload it to some registry in case there is a release. If you send me the required commands, I could extend the workflow.

Also interesting: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

### CODE REVIEW

**Comment by kherud** [comment]
Hey @rkaminsk , thank you very much! Sorry for the late reply, unfortunately I was on vacation that week and missed the notification. Ironically I saw the PR, because I was working on the same thing in the mean time. Since you have much more experience with this, I would be very grateful if you could have a look over what [I came up with](https://github.com/kherud/jclingo/blob/master/.github/workflows/release.yaml).

I took inspiration from the way `cibuildwheel` internally works, which the clingo python bindings seem to get build with:

- for macos native github runners are used (easy x64/amd64 support)
- for windows also native runners with cmake generators are used (also easy 32/64 bit x64/arm64 support)
- for linux builds I went with [dockcross](https://github.com/dockcross/dockcross). Currently only x86, x86_64, and arm64 are supported, but adding more platforms should be trivial. I'm not a C++ person, but there really seems to be no easy/established way to cross-compile for multiple platforms. Do you have any suggestions?

The `matrix.target.name` is the directory name JNA should find the respective library in. All directories are uploaded with `upload-artifact` using the same name, so they can later be easily downloaded to the Java resources directory.

For publishing the jar there are three options:

- Currently we host the jar at our denkbares repository, but I think this is the worst option, since people have to trust and rely on a third party repository.
- Maven Central: This is arguably the primary and best way. However, it requires proof of ownership over the Java groupId. I used `org.potassco`, since I thought using something like `com.denkbares`, `de.kherud`, or `io.github.kherud` might be confusing to users. So I didn't go that way in the past. It would require the owner of `potassco.org` to add a DNS TXT record with the ticket id for a Maven Central repository, if you're open for that.
- GitHub Packages: I don't have experience with this so far, but I think I'll go with this option for now, since it doesn't require proof for the domain. Later additionally adding Maven Central is also possible.

Ideally, I also want to test the library on all platforms, but I have no idea how I could approach this. Do you have any recommendation?

**Comment by rkaminsk** [comment]
> Hey @rkaminsk , thank you very much! Sorry for the late reply, unfortunately I was on vacation that week and missed the notification. Ironically I saw the PR, because I was working on the same thing in the mean time. Since you have much more experience with this, I would be very grateful if you could have a look over what [I came up with](https://github.com/kherud/jclingo/blob/master/.github/workflows/release.yaml).

I'll have a look later. I did not know you were working on something.

> I took inspiration from the way `cibuildwheel` internally works, which the clingo python bindings seem to get build with:
> 
>     * for macos native github runners are used (easy x64/amd64 support)
> 
>     * for windows also native runners with cmake generators are used (also easy 32/64 bit x64/arm64 support)
> 
>     * for linux builds I went with [dockcross](https://github.com/dockcross/dockcross). Currently only x86, x86_64, and arm64 are supported, but adding more platforms should be trivial. I'm not a C++ person, but there really seems to be no easy/established way to cross-compile for multiple platforms. Do you have any suggestions?

To be honest, I was just using cibuildwheel as is. Supporting more arches is a nice addition though.

> The `matrix.target.name` is the directory name JNA should find the respective library in. All directories are uploaded with `upload-artifact` using the same name, so they can later be easily downloaded to the Java resources directory.
> 
> For publishing the jar there are three options:
> 
>     * Currently we host the jar at our denkbares repository, but I think this is the worst option, since people have to trust and rely on a third party repository.
> 
>     * Maven Central: This is arguably the primary and best way. However, it requires proof of ownership over the Java groupId. I used `org.potassco`, since I thought using something like `com.denkbares`, `de.kherud`, or `io.github.kherud` might be confusing to users. So I didn't go that way in the past. It would require the owner of `potassco.org` to add a DNS TXT record with the ticket id for a Maven Central repository, if you're open for that.

I can add a TXT record. We could even move the project to potassco. I would make you admin of the project once moved. Of course only if you are fine with this.

>     * GitHub Packages: I don't have experience with this so far, but I think I'll go with this option for now, since it doesn't require proof for the domain. Later additionally adding Maven Central is also possible.

Sounds good.

> Ideally, I also want to test the library on all platforms, but I have no idea how I could approach this. Do you have any recommendation?

Shouldn't it be possible to simply run the tests with maven? Since you are using docker, it's close to running it one the target platform.

Thanks for your efforts!

**Comment by kherud** [comment]
> I can add a TXT record.

Awesome! I created a request for a new repository here https://issues.sonatype.org/browse/OSSRH-96639 there is already a bot comment on the DNS TXT record that has to be set.

> We could even move the project to potassco. I would make you admin of the project once moved. Of course only if you are fine with this.

Yes, I think that would be helpful to people. I developed most of the initial binding on company time and it was a challenge to even publish this on GitHub instead of the denkbares repo. But I'll ask for permission.

> Shouldn't it be possible to simply run the tests with maven? Since you are using docker, it's close to running it one the target platform.

I also want to test for all architectures. For example with windows arm, arm64, and x86 this could be challenging. Even if there are docker images, they probably just have cross-compilers, but can't run the code. In particular 32 bit could be an unknown source of error, I think.

**Comment by rkaminsk** [comment]
> > I can add a TXT record.
> 
> Awesome! I created a request for a new repository here https://issues.sonatype.org/browse/OSSRH-96639 there is already a bot comment on the DNS TXT record that has to be set.

I added the record.

> > We could even move the project to potassco. I would make you admin of the project once moved. Of course only if you are fine with this.
> 
> Yes, I think that would be helpful to people. I developed most of the initial binding on company time and it was a challenge to even publish this on GitHub instead of the denkbares repo. But I'll ask for permission.

Okay. Then I'll let you handle the legal stuff. :smile: My intend was just to increase visibility of the project.

> > Shouldn't it be possible to simply run the tests with maven? Since you are using docker, it's close to running it one the target platform.
> 
> I also want to test for all architectures. For example with windows arm, arm64, and x86 this could be challenging. Even if there are docker images, they probably just have cross-compilers, but can't run the code. In particular 32 bit could be an unknown source of error, I think.

You could try to find docker containers with java setups...

At least clingo should run fine on 32bit. Having just one 32bit test with java would probably already be enough. The involved JNA code should be pretty generic across platforms.

**Comment by kherud** [comment]
Clingo is now officially available via Maven 🎉

**Pull request merged**
